version: "3.8"
services:
  application:
    build: .
    restart: always
    ports:
      - 3001:3001
      - $PORT:$PORT
    environment:
      WAIT_HOSTS: db:5432
      DATABASE_URL: postgresql://postgres:password@db:5432
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - 5432:5432
  test-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - 5433:5432
